// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package eventtest

import (
	"sync"
	"github.com/ONSdigital/dp-observation-importer/observation"
)

var (
	lockObservationMapperMockMap	sync.RWMutex
)

// ObservationMapperMock is a mock implementation of ObservationMapper.
//
//     func TestSomethingThatUsesObservationMapper(t *testing.T) {
//
//         // make and configure a mocked ObservationMapper
//         mockedObservationMapper := &ObservationMapperMock{ 
//             MapFunc: func(row string, instanceID string) (*observation.Observation, error) {
// 	               panic("TODO: mock out the Map method")
//             },
//         }
//
//         // TODO: use mockedObservationMapper in code that requires ObservationMapper
//         //       and then make assertions.
// 
//     }
type ObservationMapperMock struct {
	// MapFunc mocks the Map method.
	MapFunc func(row string, instanceID string) (*observation.Observation, error)

	// calls tracks calls to the methods.
	calls struct {
		// Map holds details about calls to the Map method.
		Map []struct {
			// Row is the row argument value.
			Row string
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
}

// Map calls MapFunc.
func (mock *ObservationMapperMock) Map(row string, instanceID string) (*observation.Observation, error) {
	if mock.MapFunc == nil {
		panic("moq: ObservationMapperMock.MapFunc is nil but ObservationMapper.Map was just called")
	}
	callInfo := struct {
		Row string
		InstanceID string
	}{
		Row: row,
		InstanceID: instanceID,
	}
	lockObservationMapperMockMap.Lock()
	mock.calls.Map = append(mock.calls.Map, callInfo)
	lockObservationMapperMockMap.Unlock()
	return mock.MapFunc(row, instanceID)
}

// MapCalls gets all the calls that were made to Map.
// Check the length with:
//     len(mockedObservationMapper.MapCalls())
func (mock *ObservationMapperMock) MapCalls() []struct {
		Row string
		InstanceID string
	} {
	var calls []struct {
		Row string
		InstanceID string
	}
	lockObservationMapperMockMap.RLock()
	calls = mock.calls.Map
	lockObservationMapperMockMap.RUnlock()
	return calls
}
