// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package eventtest

import (
	"github.com/ONSdigital/dp-observation-importer/observation"
	"sync"
)

var (
	lockObservationMapperMockMap sync.RWMutex
)

// ObservationMapperMock is a mock implementation of ObservationMapper.
//
//     func TestSomethingThatUsesObservationMapper(t *testing.T) {
//
//         // make and configure a mocked ObservationMapper
//         mockedObservationMapper := &ObservationMapperMock{
//             MapFunc: func(row string, rowIndex int64, instanceID string) (*observation.Observation, error) {
// 	               panic("TODO: mock out the Map method")
//             },
//         }
//
//         // TODO: use mockedObservationMapper in code that requires ObservationMapper
//         //       and then make assertions.
//
//     }
type ObservationMapperMock struct {
	// MapFunc mocks the Map method.
	MapFunc func(row string, rowIndex int64, instanceID string) (*observation.Observation, error)

	// calls tracks calls to the methods.
	calls struct {
		// Map holds details about calls to the Map method.
		Map []struct {
			// Row is the row argument value.
			Row string
			// RowIndex is the rowIndex argument value.
			RowIndex int64
			// InstanceID is the instanceID argument value.
			InstanceID string
		}
	}
}

// Map calls MapFunc.
func (mock *ObservationMapperMock) Map(row string, rowIndex int64, instanceID string) (*observation.Observation, error) {
	if mock.MapFunc == nil {
		panic("moq: ObservationMapperMock.MapFunc is nil but ObservationMapper.Map was just called")
	}
	callInfo := struct {
		Row        string
		RowIndex   int64
		InstanceID string
	}{
		Row:        row,
		RowIndex:   rowIndex,
		InstanceID: instanceID,
	}
	lockObservationMapperMockMap.Lock()
	mock.calls.Map = append(mock.calls.Map, callInfo)
	lockObservationMapperMockMap.Unlock()
	return mock.MapFunc(row, rowIndex, instanceID)
}

// MapCalls gets all the calls that were made to Map.
// Check the length with:
//     len(mockedObservationMapper.MapCalls())
func (mock *ObservationMapperMock) MapCalls() []struct {
	Row        string
	RowIndex   int64
	InstanceID string
} {
	var calls []struct {
		Row        string
		RowIndex   int64
		InstanceID string
	}
	lockObservationMapperMockMap.RLock()
	calls = mock.calls.Map
	lockObservationMapperMockMap.RUnlock()
	return calls
}
